# coding: utf-8

"""
    マネーフォワードクラウド会計Plus API

    マネーフォワードクラウド会計PlusのAPI  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: api.acplus.support@moneyforward.co.jp
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import moneyforward_acplus
from moneyforward_acplus.models.account import Account  # noqa: E501
from moneyforward_acplus.rest import ApiException

class TestAccount(unittest.TestCase):
    """Account unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Account
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = moneyforward_acplus.models.account.Account()  # noqa: E501
        if include_optional :
            return Account(
                account_financial_statements_type = '0',
                category_name = '0',
                account_id = 56,
                account_name = '0',
                tax = '0',
                is_enabled = True
            )
        else :
            return Account(
                account_financial_statements_type = '0',
                category_name = '0',
                account_id = 56,
                account_name = '0',
                tax = '0',
                is_enabled = True,
        )

    def testAccount(self):
        """Test Account"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
